name: SurfUtilities
version: '0.0.3 Alpha'
main: me.luhen.surfutilities.Main
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
commands:
  sellclaim:
  shopmenu:
  su:

softdepend:
  - GriefPrevention
  - ChestShop